### ISSUE TITLE
External link icon disappeared from links 

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/developer.ubuntu.com#197] opened 2017-01-11 13:36 UTC
We used to display the external link icon automatically - now they are not showing

**Comment by nottrobin** [comment] 2017-01-16 14:17
This is now fixed. Oddly, this issue was caused by the `global.js` and `global.css` links redirecting to HTTP versions of those files. I've updated those redirects, and now the external icon is showing again.

**Closed as completed by nottrobin** 2017-01-16 14:17 UTC
Labels: Type: Bug, Priority: High
