### ISSUE TITLE
Feed failed to load

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/developer.ubuntu.com#339] opened 2018-01-23 10:56 UTC
Visited developer.ubuntu.com home page and saw this.

![image](https://user-images.githubusercontent.com/1841272/35272126-1e8e8850-002c-11e8-82e9-8504a7da14df.png)

**Comment by Lukewh** [comment] 2018-02-15 15:29
Duplicate of https://github.com/canonical-websites/developer.ubuntu.com/issues/331. Thanks for the report

**Closed as completed** 2018-02-15 15:30 UTC
