### ISSUE TITLE
landing page "Latest Tutorials" says "Feed failed to load"

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/developer.ubuntu.com#345] opened 2018-02-09 02:37 UTC
The landing page at developer.ubuntu.com has a section at the bottom titled "Latest Tutorials".

It currently has an error that says:

"Feed failed to load. If you have time, please file an issue."

So here I am, filing an issue :)

**Comment by Lukewh** [comment] 2018-02-15 15:30
Duplicate of https://github.com/canonical-websites/developer.ubuntu.com/issues/331. Thanks for the report

**Closed as completed by Lukewh** 2018-02-15 15:30 UTC
