### ISSUE TITLE
"Feed failed to load"

### ISSUE THREAD

**Issue by dkfrayne** [canonical-web-and-design/developer.ubuntu.com#346] opened 2018-02-10 08:09 UTC
[https://developer.ubuntu.com/?_ga=2.244198598.212031325.1518249963-1103884530.1518249963](url)

**Comment by Lukewh** [comment] 2018-02-15 15:30
Duplicate of https://github.com/canonical-websites/developer.ubuntu.com/issues/331. Thanks for the report

**Closed as completed by Lukewh** 2018-02-15 15:30 UTC
