### ISSUE TITLE
Feed failed to load

### ISSUE THREAD

**Issue by sk8nfool** [canonical-web-and-design/developer.ubuntu.com#350] opened 2018-02-22 14:54 UTC
went to https://developer.ubuntu.com/ and the "Latest Tutorials" section asked me to file this report.

**Comment by anthonydillon** [comment] 2018-03-18 22:23
Thank you very much for reporting this issue. It has been triaged and will be actioned soon.

**Comment by nottrobin** [comment] 2018-03-21 09:44
Duplicate of #349

**Closed as completed by nottrobin** 2018-03-21 09:44 UTC
Labels: Type: Bug, Priority: Critical
